version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pizza_db
    restart: always
    environment:
      POSTGRES_DB: pizza_shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

