version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: pizza_postgres
    restart: always
    environment:
      POSTGRES_DB: pizzadb
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: userpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

