# Denne Docker Compose-fil konfigurerer og starter en PostgreSQL-container, eksponerer port 5432,
# indlæser miljøvariabler, og kører initiale SQL-scripts ved opstart.
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql # new line

volumes:
  postgres_data: