version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pizza_shop_db
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: ownerpass
      POSTGRES_DB: pizza_shop
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: